version: '3'

services:
  mysql:
    image: mysql:8.0.32
    container_name: my_mysql
    restart: always
    networks:
      - mynetwork
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: my_phpmyadmin
    restart: always
    networks:
      - mynetwork
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=500M
    ports:
      - "3306:80"

  nodered:
    image: nhdinh/node-red:2.2.2
    container_name: my_nodered
    restart: always
    networks:
      - mynetwork
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - node_red_data:/data
    ports:
      - "1880:1880"

networks:
  mynetwork:
    driver: bridge
volumes:
  mysql_data: {}
  node_red_data: {}